#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q mThM.q
#$ -l mres=192G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N PROJECT_trim
#$ -o logs/PROJECT_trim.log
#
# ----------------Modules------------------------- #
 module load ~/modulefiles/miniconda
 source activate trimmomatic
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
sh trimmomatic_genomeskimming_multi_hydra.sh
#
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the trimmomatic environment,
# and runs the shell script that will trim all paired samples using trimmomatic.
# Before using, change -N and -o under Parameters to your project name.