---
title: "Pocillopora genotype origin map"
author: "Mike Connelly"
date: "01/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r packages, message=FALSE}
library("tidyverse")
library("raster") #for processing some spatial data
library("rnaturalearth") #for downloading shapefiles
library("sf") #for processing shapefiles
library("elevatr") #for downloading elevation data
library("dplyr") #to keep things tidy
library("magrittr") #to keep things very tidy
library("ggspatial") #for scale bars and arrows
library("ggplot2") #for tidy plotting
library("ggpubr") #for easy selection of symbols
library("colourpicker") #for easy selection of colors
library("rnaturalearthhires")
library("maps") # for getting pacific-centered map
library("scatterpie") # for plotting proportions of different lineages on map
library("ggnewscale") # for adding new fill scale to keep elevation
library("ggrepel") # for adding labels to plot
```

## Prepare map data
```{r load shapefiles, message=FALSE}
# Load shapefiles from rnaturalearth package
map <- ne_countries(scale = 10, returnclass = "sf")
# 
states <- ne_states(returnclass = "sf")
# 
ocean <- ne_download(scale = 10, type = 'ocean', 
                   category = 'physical', returnclass = 'sf')
# 
rivers <- ne_download(scale = 10, type = 'rivers_lake_centerlines', 
                    category = 'physical', returnclass = 'sf')
# 
reefs <- ne_download(scale = 10, type = 'reefs',
                     category = "physical", returnclass = 'sf')
#
minor_islands <- ne_download(scale = 10, type = 'minor_islands',
                             category = "physical", returnclass = 'sf')
#
minor_islands_coastline <- ne_download(scale = 10, type = 'minor_islands_coastline',
                             category = "physical", returnclass = 'sf')
```
```{r Quick check on basic shapefiles, echo = FALSE, fig.align= "center", fig.width= 6}
quickCheck <-
  ggplot() +
  geom_sf(data = ocean, color = "black", size = 0.05, fill = "#def3f6") +
  geom_sf(data = reefs, color = "red", size = 0.05, fill = "red") +
  geom_sf(data = rivers, color = "blue", size = 0.05) +
  geom_sf(data = states, color = "black", size = 0.05, fill = "#f5f5f5", alpha = 0.5) +
  geom_sf(data = minor_islands, color = "black", size = 0.05, fill = "green") +
  theme(panel.grid.major = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA))
par(mar = c(0.5, 0.5, 0.5, 0.5))
quickCheck
```
```{r etp_define}
etp_countries <- c("Mexico", "Guatemala", "El Salvador", "Nicaragua", "Honduras", "Costa Rica", "Panama", "Colombia", "Ecuador", "Peru")
focalArea <- map %>% filter(admin %in% etp_countries)
```
```{r define map extent}
limit <- st_buffer(focalArea, dist = 0.1) %>% st_bbox()

clipLimit <- st_buffer(focalArea, dist = 0.5) %>% st_bbox()

limitExtent <- as(extent(clipLimit), 'SpatialPolygons')

crs(limitExtent) <- "+proj=longlat +datum=WGS84 +no_defs"
```
```{r Show map and clipping extent, echo = FALSE, fig.align= "center", warning = FALSE}
par(mar = c(0.5, 0.5, 0.5, 0.5))
plot(as(extent(clipLimit), 'SpatialPolygons'), lty="dashed")
plot(as(extent(limit), 'SpatialPolygons'), add = TRUE)
plot(focalArea, col = "#005293", add = TRUE)
```

## Small-area maps
```{r test Coiba map}
par(mar = c(0.5, 0.5, 0.5, 0.5))
CoibaMapTest <-
  ggplot() +
  # geom_tile(data = elevDF, aes(x=x, y=y, fill=elevation), alpha =0.4)+
  # scale_fill_gradient(low="#a3a0a0", high= "#000000", 
  #                     na.value="transparent")+
  geom_sf(data = ocean, size = 0.05, fill = "#add8e6")+
  geom_sf(data = rivers, color = "#d7f2fa", size = 0.5)+
  geom_sf(data = states, color = "black", size = 0.05, fill = "#f5f5f5", alpha = 0.2)+
  geom_sf(data = map, color = "black", size = 0.1, fill = "#f5f5f5", alpha = 0.2)+
  geom_sf(data = minor_islands, color = "black", size = 0.1, fill = "#f5f5f5") +
    coord_sf(
    xlim = c(-82.25, -81.25),
    ylim = c(7, 8)) +
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
  panel.background = element_rect(fill = "#f0f8ff"),
  panel.border = element_rect(fill = NA))
CoibaMapTest
```
```{r test Perlas map}
par(mar = c(0.5, 0.5, 0.5, 0.5))
PerlasMapTest <-
  ggplot() +
  # geom_tile(data = elevDF, aes(x=x, y=y, fill=elevation), alpha =0.4)+
  # scale_fill_gradient(low="#a3a0a0", high= "#000000", 
  #                     na.value="transparent")+
  geom_sf(data = ocean, size = 0.05, fill = "#add8e6")+
  geom_sf(data = rivers, color = "#d7f2fa", size = 0.5)+
  geom_sf(data = states, color = "black", size = 0.05, fill = "#f5f5f5", alpha = 0.2)+
  geom_sf(data = map, color = "black", size = 0.1, fill = "#f5f5f5", alpha = 0.2)+
        geom_sf(data = minor_islands, color = "black", size = 0.1, fill = "#f5f5f5") +
    coord_sf(
    xlim = c(-79.5, -78.5),
    ylim = c(8, 9)) +
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
  panel.background = element_rect(fill = "#f0f8ff"),
  panel.border = element_rect(fill = NA))
PerlasMapTest
```
```{r}
CoibaMapTest +
    geom_point(data = samples_sites[grepl("Coiba", samples_sites$`Region:Site`), ],
             aes(x = `Longitude`, y = `Latitude`, size = `n`, fill = `Region:Site`),
             shape = 21, alpha = 0.9, color = "black", stroke = 0.5,
             # position = position_jitter(width = 0.1, height = 0.1, seed = 3),
             show.legend = F)
#
PerlasMapTest +
    geom_point(data = samples_sites[grepl("Perlas", samples_sites$`Region:Site`), ],
             aes(x = `Longitude`, y = `Latitude`, size = `n`, fill = `Region:Site`),
             shape = 21, alpha = 0.9, color = "black", stroke = 0.5,
             # position = position_jitter(width = 0.1, height = 0.1, seed = 3),
             show.legend = F)
```

## Plot proportions of *Pocillopora* mtORF lineages on map with scatterpie
```{r sample_data_import}
source("./R/sample_import.R")
samples <- all_samples
```
```{r}
# use only unique genotypes 
samples <- samples_noclones
```

### Prepare map metadata
```{r sample_data_tidy}
# filter out irrelevant samples, select only informative columns
region_coords <- samples %>% group_by(Region) %>% summarise(Longitude=mean(Longitude), Latitude=mean(Latitude))
samples_select <- samples #%>% 
  # dplyr::filter(!is.na(`Sampling Date`)) %>% 
  # dplyr::filter(!is.na(`Latitude`)) %>% 
  # dplyr::select(`Sample ID`:`Depth (ft)`)
# count sample number across different locations
samples_regions <- samples_select %>% 
  group_by(`Region`) %>% 
  count() %>% 
  left_join(region_coords, by = "Region")
samples_locations <- samples_select %>% 
  group_by(`Region`, `Site`, `Latitude`, `Longitude`) %>% 
  count()
samples_sites <- samples_select %>% 
  group_by(`Region:Site`, `Latitude`, `Longitude`) %>% 
  count()
```
```{r prepare_scatterpie_data}
# see example at: https://cran.r-project.org/web/packages/scatterpie/vignettes/scatterpie.html
  
regions_mtorfs <- samples %>% 
  group_by(`Region`, mtorf_type) %>% 
  dplyr::count() %>% 
  pivot_wider(names_from = mtorf_type, values_from = n, values_fill = 0) %>% 
  # dplyr::rename("Type 1" = Type_1, "Type 3" = Type_3) %>% 
  mutate("radius" = (`Type 1a` + `Type 2` + `Type 3a` + `Type 3b`)/50) %>% 
  left_join(region_coords, by = "Region")
#
sites_mtorfs <- samples %>% 
  group_by(`Region:Site`, mtorf_type) %>% 
  dplyr::count() %>% 
  pivot_wider(names_from = mtorf_type, values_from = n, values_fill = 0) %>% 
  # dplyr::rename("Type 1" = Type_1, "Type 3" = Type_3) %>% 
  mutate("radius" = (`Type 1a` + `Type 2` + `Type 3a` + `Type 3b`)/20) %>% 
  left_join(samples_sites, by = "Region:Site") %>% dplyr::select(-n)
#
regions_species <- samples %>% 
  group_by(`Region`, Species) %>% 
  dplyr::count() %>% 
  pivot_wider(names_from = Species, values_from = n, values_fill = 0) %>% 
  # dplyr::rename("Type 1" = Type_1, "Type 3" = Type_3) %>% 
  mutate("sum" = (`P. effusa` + `P. grandis` + `P. meandrina` + `P. verrucosa 3a` + `P. verrucosa 3b`)) %>%
  mutate("radius" = (`P. effusa` + `P. grandis` + `P. meandrina` + `P. verrucosa 3a` + `P. verrucosa 3b`)/50) %>% 
  left_join(region_coords, by = "Region")
```

### Plot maps with metadata
#### Manually-Assigned Species Scatterpie
```{r assigned species: powerpoint}
pdf(file="./outputs/figures/sicb/Pocillopora_origins_map_scatterpie.pdf", width = 8, height = 4.25)
par(mar = c(0.5, 0.5, 0.5, 0.5))
elevMapTest <-
  ggplot() +
  geom_sf(data = ocean, color = "black", size = 0.1, fill = "aliceblue") +
  geom_sf(data = rivers, color = "#d7f2fa", size = 0.5)+
  geom_sf(data = states, color = "darkgrey", size = 0.1, fill = "antiquewhite", alpha = 0.5) +
  geom_sf(data = map, color = "black", size = 0.1, fill = "antiquewhite", alpha = 0.5) +
    coord_sf(
    xlim = c(-112, -76),
    ylim = c(-2, 16)) +
  #
  new_scale_fill() +
  geom_scatterpie(aes(x = Longitude, y = Latitude, group = `Region`, r = 1),
                    data = regions_species, cols = c("P. effusa", "P. grandis", "P. meandrina", "P. verrucosa 3a", "P. verrucosa 3b"), size = 5, alpha = .8) + 
  scale_fill_manual(values = c("purple", "darkorange1", "gold", "turquoise2", "turquoise4"), name = "Species") +
  #
  geom_label_repel(aes(x = Longitude, y = Latitude, label = sum), size = 2, box.padding = 0.5, min.segment.length = 2, seed = 3, data = regions_species) +
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "#f0f8ff"),
        panel.border = element_rect(fill = NA),
        plot.title = element_blank(),
        plot.subtitle = element_blank(),
        axis.title = element_blank(), 
        axis.text = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8, face = "italic"),
        legend.position = c(0.14, 0.28)) +
  ggtitle(expression(italic("Pocillopora")*' species distribution and genotype counts'), subtitle = "All unique genotypes (N = 229)")
# subtitle = "All East Pacific samples (N = 337)")
elevMapTest
dev.off()
```
```{r}
png(file="./outputs/figures/sicb/Pocillopora_origins_map_scatterpie.png", width = 8, height = 3.75, units = "in", res = 300, type = "cairo-png")
elevMapTest
dev.off()
```

### NGSAdmix clusters (K = 6) Scatterpie
### Figure 1C
```{r}
# first, join NGSAdmix no-clones sample species assignments to no-clones sample metadata
samples_noclones_ngsadmix_meta <- left_join(samples_noclones, samples_noclones_ngsadmix, by = "Sample ID")
```
```{r prepare_ngsadmix_scatterpie_data}
# see example at: https://cran.r-project.org/web/packages/scatterpie/vignettes/scatterpie.html
#
regions_ngsadmix_pops <- samples_noclones_ngsadmix %>%
  group_by(`Region`, `NGSAdmix K6 Species`) %>% 
  dplyr::count() %>% 
  mutate("Region" = factor(`Region`, levels = region_order_longitude, ordered = T),
         "NGSAdmix K6 Species" = factor(`NGSAdmix K6 Species`, levels = ngsadmix_spp, ordered = T)) %>% 
  pivot_wider(names_from = `NGSAdmix K6 Species`, values_from = n, values_fill = 0) %>%
  mutate("sum" = (rowSums(across(contains("P")))) + Unassigned) %>%
  mutate("radius" = `sum`/50) %>%
  left_join(region_coords, by = "Region")
```
```{r}
par(mar = c(0.5, 0.5, 0.5, 0.5))
elevMapTest <-
  ggplot() +
  geom_sf(data = ocean, color = "black", size = 0.1, fill = "aliceblue") +
  geom_sf(data = rivers, color = "#d7f2fa", size = 0.5)+
  geom_sf(data = states, color = "darkgrey", size = 0.1, fill = "antiquewhite", alpha = 0.5) +
  geom_sf(data = map, color = "black", size = 0.1, fill = "antiquewhite", alpha = 0.5) +
    coord_sf(
    xlim = c(-112, -76),
    ylim = c(-2, 12)) +
  #
  new_scale_fill() +
  geom_scatterpie(aes(x = Longitude, y = Latitude, group = `Region`, r = 1),
                    data = regions_ngsadmix_pops, cols = ngsadmix_spp, size = 5, alpha = .8) + 
  scale_fill_manual(values = ngsadmix_pop_colors_k6, name = "NGSadmix population") +
  #
  geom_label_repel(aes(x = Longitude, y = Latitude, label = sum), size = 2, box.padding = 0.5, min.segment.length = 2, seed = 3, data = regions_ngsadmix_pops) +
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  scale_y_continuous(breaks = (seq(0,15,5))) +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "#f0f8ff"),
        panel.border = element_rect(fill = NA),
        plot.title = element_blank(),
        plot.subtitle = element_blank(),
        axis.title = element_blank(), 
        axis.text = element_text(size = 10),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        # legend.position = c(0.14, 0.28),
        legend.position = "none") +
  ggtitle(expression(italic("Pocillopora")*' species distribution and genotype counts'), subtitle = "All non-admixed genotypes (N = 211)")
# subtitle = "All East Pacific samples (N = 337)")
elevMapTest
```
```{r fig1C_scatterpie_map}
pdf("./outputs/figures/Fig1C_ngsadmix_k6_map.pdf", width = 6.65)
elevMapTest
dev.off()
```

### Table S1: Sample metadata
```{r table S1: basic sample info table}
# write out basic sample information table to host on GitHub
samples %>%
  arrange(`Sequence Round`, `Sample ID`) %>%
  dplyr::select(-Set:-SINGLETON, -haplotype:-Species) %>% 
  mutate(`Sample ID` = str_remove_all(`Sample ID`, "_AP3X.*")) %>%
  write_csv(., "./data/AllSamples_MetadataTable.csv")
```

### Sample Numbers Figure
```{r sample numbers: powerpoint}
pdf(file="./outputs/figures/Pocillopora_origins_map_numbers.pdf", width = 7.2, height = 4)
par(mar = c(0.5, 0.5, 0.5, 0.5))
map_samplenumbers <-
  ggplot() +
  geom_sf(data = ocean, color = "black", size = 0.1, fill = "aliceblue") +
  geom_sf(data = rivers, color = "#d7f2fa", size = 0.5)+
  geom_sf(data = states, color = "darkgrey", size = 0.1, fill = "antiquewhite", alpha = 0.5) +
  geom_sf(data = map, color = "black", size = 0.1, fill = "antiquewhite", alpha = 0.5) +
    coord_sf(
    xlim = c(-112, -76),
    ylim = c(-2, 16)) +
  #
  new_scale_fill() +
  geom_point(aes(x = Longitude, y = Latitude, size = n, fill = Region),
                    data = samples_regions, shape = 21, alpha = .8, color = "black", show.legend = F) +
  scale_size_continuous(range = c(0.4, 10), limits = c(0, 80), breaks = c(10, 20, 40, 80), name = "# samples") +
  scale_fill_manual(values = region_colors) +
  #
  labs(x="Longitude", y="Latitude") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "#f0f8ff"),
        panel.border = element_rect(fill = NA),
        plot.title = element_text(size = 16),
        axis.title = element_blank(), 
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.position = c(0.09, 0.26)) +
  ggtitle(expression('East Pacific '*italic("Pocillopora")*' sampling locations'))
map_samplenumbers
dev.off()
```
```{r}
png(file="./outputs/figures/Pocillopora_origins_map_numbers.png", type = "cairo-png", width = 7.2, height = 4, units = "in", res = 300)
map_samplenumbers
dev.off()
```
```{r}
ggsave()
ggsave("./outputs/figures/Pocillopora_origins_map_numbers.png", plot = map_samplenumbers, device = "png", dpi = 300, width = 7.2, height = 4, units = "in")
```
