---
title: "ETP Pocillopora sample origin maps"
author: "Mike Connelly"
date: "02/22/2022"
output: html_document
---
## Setup packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r setup packages}
library("tidyverse")
library("marmap") #for downloading and plotting bathymetry and topography data
library("raster") #for processing some spatial data
library("rnaturalearth") #for downloading shapefiles
library("rnaturalearthdata")
# library("rnaturalearthhires")
library("sf") #for processing shapefiles
library("elevatr") #for downloading elevation data
library("dplyr") #to keep things tidy
library("magrittr") #to keep things very tidy
library("ggspatial") #for scale bars and arrows
library("ggplot2") #for tidy plotting
library("ggpubr") #for easy selection of symbols
library("colourpicker") #for easy selection of colors
# visualization packages
library("scatterpie") # for plotting proportions of different lineages on map
library("ggnewscale") # for adding new fill scale to keep elevation
library("ggrepel") # for adding labels to plot
library("extrafont")
library("extrafontdb")
library("patchwork")
```
```{r}
theme_set(theme_bw())
```
## Sample import
```{r sample_data_import}
samples <- read_csv("./data/pocillopora_samples.csv")
```
```{r}
all_samples <- read_csv("./data/pocillopora_samples_003.csv")
stri_samples <- read_csv("./data/etp_samples.txt")
```
```{r}
samples <- filter(all_samples, all_samples$`Sample ID` %in% stri_samples$`Sample ID`)
samples$`Region:Site` <- paste(samples$Region, samples$Site, sep = ":")
```
```{r}
unsamples <- filter(all_samples, all_samples$`Sample ID` %notin% stri_samples$`Sample ID`)
```

```{r sample_data_tidy}
# filter out irrelevant samples, select only informative columns
samples_select <- samples #%>% 
  # dplyr::filter(!is.na(`Sampling Date`)) %>% 
  # dplyr::filter(!is.na(`Latitude`)) %>% 
  # dplyr::select(`Sample ID`:`Depth (ft)`)
# count sample number across different locations
samples_locations <- samples_select %>% 
  group_by(`Region`, `Site`, `Latitude`, `Longitude`) %>% 
  count()
samples_sites <- samples_select %>% 
  group_by(`Region:Site`, `Latitude`, `Longitude`) %>% 
  count()
```

```{r}
# samples_locations$Longitude <- ifelse(samples_locations$Longitude < 0, (samples_locations$Longitude + 360), (samples_locations$Longitude)) 
# samples_locations$Study <- factor(samples_locations$Study, levels = study_levels, ordered = TRUE)
```
## Colors
```{r colors}
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
gcolors <- gg_color_hue(n_distinct(samples_locations$Region))
# gcolors <- gg_color_hue(2)
site_colors <- c("red", "red4", "maroon", "maroon4", "darkgreen", "green4", "green", "lightgreen", "cyan", "cyan4", "turquoise", "turquoise4")
site_colors <- c("gold1", "blue", "darkblue", "steelblue", "lightblue", "darkorange3","darkorange", "orange", "orangered", "cyan", "cyan3", "cyan4", "turquoise", "lightgreen")
```


## Create mapping sf data objects
```{r download shapefiles, message=FALSE}
# Load shapefiles from rnaturalearth package
map <- ne_countries(scale = 10, returnclass = "sf")
# 
states <- ne_states(returnclass = "sf")
# 
# ocean <- ne_download(scale = 10, type = 'ocean', 
#                    category = 'physical', returnclass = 'sf')
#
# rivers <- ne_download(scale = 10, type = 'rivers_lake_centerlines', 
#                     category = 'physical', returnclass = 'sf')
# 
# reefs <- ne_download(scale = 10, type = 'reefs',
#                      category = "physical", returnclass = 'sf')
```
```{r load shapefiles}
ocean <- ne_load(scale = 10, type = "ocean", category = "physical", destdir = "data/spatial_data/ne_10m_ocean", returnclass = "sf")
#
rivers <- ne_load(scale = 10, type = "rivers_lake_centerlines", category = "physical", destdir = "data/spatial_data/ne_10m_rivers_lake_centerlines", returnclass = "sf")
#
reefs <- ne_load(scale = 10, type = "reefs", category = "physical", destdir = "data/spatial_data/ne_10m_reefs", returnclass = "sf")
#
```
```{r load bathymetry shapefiles}
bathymetry_K <- ne_load(scale = 10, type = "bathymetry_K_200", category = "physical", destdir = "data/spatial_data/ne_10m_bathymetry_all", returnclass = "sf")
#
bathymetry_J <- ne_load(scale = 10, type = "bathymetry_J_1000", category = "physical", destdir = "data/spatial_data/ne_10m_bathymetry_all", returnclass = "sf")
#
bathymetry_I <- ne_load(scale = 10, type = "bathymetry_I_2000", category = "physical", destdir = "data/spatial_data/ne_10m_bathymetry_all", returnclass = "sf")
#
bathymetry_H <- ne_load(scale = 10, type = "bathymetry_H_3000", category = "physical", destdir = "data/spatial_data/ne_10m_bathymetry_all", returnclass = "sf")
#
bathymetry_G <- ne_load(scale = 10, type = "bathymetry_G_4000", category = "physical", destdir = "data/spatial_data/ne_10m_bathymetry_all", returnclass = "sf")
#
bathymetry_F <- ne_load(scale = 10, type = "bathymetry_F_5000", category = "physical", destdir = "data/spatial_data/ne_10m_bathymetry_all", returnclass = "sf")
#
```
```{r Quick check on basic shapefiles, echo = FALSE, fig.align= "center", fig.width= 6}
quickCheck <-
  ggplot() +
  geom_sf(data = ocean, color = "black", size = 0.05, fill = "#def3f6") +
  geom_sf(data = reefs, color = "red", size = 0.05, fill = "red") +
  geom_sf(data = rivers, color = "blue", size = 0.05) +
  geom_sf(data = states, color = "black", size = 0.05, fill = "#f5f5f5", alpha = 0.5) +
  geom_sf(data = bathymetry_K, color = "red", size = 0.1) +
  geom_sf(data = bathymetry_J, color = "orange", size = 0.1) +
  geom_sf(data = bathymetry_I, color = "yellow", size = 0.1) +
  geom_sf(data = bathymetry_H, color = "green", size = 0.1) +
  theme(panel.grid.major = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA))
par(mar = c(0.5, 0.5, 0.5, 0.5))
quickCheck
```
```{r}
focalArea <- map %>% filter(admin == "Panama" | admin == "Costa Rica")
```
```{r define map extent}
limit <- st_buffer(focalArea, dist = 0.1) %>% st_bbox()

clipLimit <- st_buffer(focalArea, dist = 0.5) %>% st_bbox()

limitExtent <- as(extent(clipLimit), 'SpatialPolygons')

crs(limitExtent) <- "+proj=longlat +datum=WGS84 +no_defs"
```
```{r Show map and clipping extent, echo = FALSE, fig.align= "center", warning = FALSE}
par(mar = c(0.5, 0.5, 0.5, 0.5))
plot(as(extent(clipLimit), 'SpatialPolygons'), lty="dashed")
plot(as(extent(limit), 'SpatialPolygons'), add = TRUE)
plot(focalArea, col = "#005293", add = TRUE)
```
```{r obtain elevation data}
elev<-get_elev_raster(locations = limitExtent, z = 6, override_size_check = T)

elevDF<-as.data.frame(elev, xy=TRUE)

colnames(elevDF)<-c("x", "y", "elevation")

elevDF[, 3][elevDF[, 3] < 1500] <- NA
```
```{r Test elevation map, echo = FALSE, fig.align= "center", warning = FALSE}
par(mar = c(0.5, 0.5, 0.5, 0.5))
elevMapTest <-
  ggplot() +
  geom_tile(data = elevDF, aes(x=x, y=y, fill=elevation), alpha =0.4)+
  scale_fill_gradient(low="#a3a0a0", high= "#000000", 
                      na.value="transparent")+
  geom_sf(data = ocean, color = "black", size = 0.05, fill = "#add8e6")+
  geom_sf(data = rivers, color = "#d7f2fa", size = 0.5)+
  geom_sf(data = states, color = "black", size = 0.05, fill = "#f5f5f5", alpha = 0.2)+
  geom_sf(data = map, color = "black", size = 0.1, fill = "#f5f5f5", alpha = 0.2)+
    coord_sf(
    xlim = c(limit["xmin"], limit["xmax"]),
    ylim = c(limit["ymin"], limit["ymax"])) +
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
  panel.background = element_rect(fill = "#f0f8ff"),
  panel.border = element_rect(fill = NA))
  ggtitle(title)
elevMapTest
```
```{r Test bathymetry map}
par(mar = c(0.5, 0.5, 0.5, 0.5))
elevMapTest <-
  ggplot() +
  geom_tile(data = elevDF, aes(x=x, y=y, fill=elevation), alpha =0.4)+
  scale_fill_gradient(low="#a3a0a0", high= "#000000", 
                      na.value="transparent")+
  geom_sf(data = ocean, color = "black", size = 0.05, fill = "#add8e6")+
  geom_sf(data = rivers, color = "#d7f2fa", size = 0.5)+
  geom_sf(data = states, color = "black", size = 0.05, fill = "#f5f5f5", alpha = 0.2)+
  geom_sf(data = map, color = "black", size = 0.1, fill = "#f5f5f5", alpha = 0.2)+
  geom_sf(data = bathymetry_K, color = "red", size = 0.1) +
  geom_sf(data = bathymetry_J, color = "orange", size = 0.1) +
  geom_sf(data = bathymetry_I, color = "yellow", size = 0.1) +
  geom_sf(data = bathymetry_H, color = "green", size = 0.1) +
  geom_sf(data = bathymetry_G, color = "blue", size = 0.1) +
  geom_sf(data = bathymetry_F, color = "purple", size = 0.1) +
    coord_sf(
    xlim = c(limit["xmin"], limit["xmax"]),
    ylim = c(limit["ymin"], limit["ymax"])) +
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
  panel.background = element_rect(fill = "#f0f8ff"),
  panel.border = element_rect(fill = NA))
  ggtitle(title)
elevMapTest
```

### Map of Pocillopora sample origins
```{r factor levels}
```

```{r}
pdf("./outputs/figures/Fig1_samples_locations_map_bathymetry.pdf")
title <- expression('Panama '*italic("Pocillopora")*' genotype origins')
par(mar = c(0.5, 0.5, 0.5, 0.5))
elevMapTest <-
  ggplot() +
  geom_sf(data = ocean, color = "black", size = 0.1, fill = "aliceblue") +
  geom_sf(data = states, color = "black", size = 0.1, fill = "antiquewhite", alpha = 0.5) +
  geom_sf(data = map, color = "black", size = 0.2, fill = "antiquewhite", alpha = 0.5) +
  geom_tile(data = elevDF, aes(x = x, y = y, fill = elevation), alpha = 0.4, show.legend = FALSE) +
  scale_fill_gradient(low="antiquewhite3", high= "black",
                      na.value="transparent", name = "Elevation (m)") +
  geom_sf(data = rivers, color = "royalblue3", size = 0.15) +
  #
  geom_sf(data = bathymetry_K, color = "red", size = 0.1) +
  geom_sf(data = bathymetry_J, color = "orange", size = 0.1) +
  geom_sf(data = bathymetry_I, color = "yellow", size = 0.1) +
  geom_sf(data = bathymetry_H, color = "green", size = 0.1) +
  geom_sf(data = bathymetry_G, color = "blue", size = 0.1) +
  #
    coord_sf(
    xlim = c(limit["xmin"], limit["xmax"]),
    ylim = c(limit["ymin"], limit["ymax"])) +
  #
  new_scale_fill() +
   geom_point(data = samples_locations, aes(x = `Longitude`, y = `Latitude`, size = `n`, fill = `Region`), shape = 21, alpha = 0.8, color = "black", stroke = 0.5,
             position = position_jitter(width = 0.2, height = 0.2, seed = 3),
             show.legend = T) +
 scale_fill_manual(values = gcolors,
                    guide = guide_legend(order = 1, override.aes = list(size = 6, shape = 21, fill = gcolors), nrow = 5, title.position = "top")) +
  scale_size(range = c(1, 5), breaks = c(1, 10, 20), limits = c(0, 20),
             guide = guide_legend(order = 2, override.aes = list(fill = "black"), nrow = 5, title.position = "top")) +
  #
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "#f0f8ff"),
        panel.border = element_rect(fill = NA),
        plot.title = element_text(size = 16),
        axis.title = element_text(size = 14), 
        axis.text = element_text(size = 10),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 10)) +
  ggtitle(title)
elevMapTest
dev.off()
```

# START HERE
## Map of Pocillopora sample origins using marmap package
```{r}
# get ETP bathymetric data
panama <- getNOAA.bathy(lon1 = -88, lon2 = -76,
                        lat1 = 4, lat2 = 12, resolution = 1)
# East Pacific from Revi's to Galapagos (to show Clipperton samples)
east_pacific <- getNOAA.bathy(lon1 = -112, lon2 = -76,
                        lat1 = -2, lat2 = 16, resolution = 2)
# East Pacific from Revi's to Rapa Nui
east_pacific_all <- getNOAA.bathy(lon1 = -120, lon2 = -74,
                        lat1 = -30, lat2 = 30, resolution = 3)
```

```{r}
summary(panama)
```
```{r}
plot(panama, image = TRUE)
scaleBathy(panama, deg = 2, x = "bottomleft", inset = 5)
```
```{r}
# Creating a custom palette of blues
blues <- c("lightsteelblue4", "lightsteelblue3",
           "lightsteelblue2", "lightsteelblue1")
# Plotting the bathymetry with different colors for land and sea
plot(panama, image = TRUE, land = TRUE, lwd = 0.1,
     bpal = list(c(0, max(panama), "grey"),
                 c(min(panama),0,blues)))
# Making the coastline more visible
plot(panama, deep = 0, shallow = 0, step = 0,
     lwd = 0.4, add = TRUE)
```
```{r}
# Plot bathy object using custom ggplot2 functions
marmap::autoplot.bathy(panama, geom=c("r", "c"), colour="white", size=0.1) + scale_fill_etopo()
```
```{r}
pdf("./outputs/figures/Fig1_samples_locations_map_bathymetry_051123.pdf", width = 8, height = 6)
title <- expression('Eastern Pacific '*italic("Pocillopora")*' genotype origins')
# Plot bathy object using custom ggplot2 functions
par(mar = c(0.5, 0.5, 0.5, 0.5))
marmap::autoplot.bathy(panama, geom=c("r", "c"), color = "white", size = 0.01) + 
  scale_fill_etopo(name = "Depth (m)") + 
  new_scale_fill() +
  geom_point(data = samples_locations,
             aes(x = `Longitude`, y = `Latitude`, size = `n`, fill = `Region`),
             shape = 21, alpha = 0.9, color = "black", stroke = 0.5,
             position = position_jitter(width = 0.2, height = 0.2, seed = 3),
             show.legend = T) +
  scale_fill_manual(values = gcolors,
                    guide = guide_legend(order = 2,
                                         override.aes = list(size = 6,
                                                             shape = 21, 
                                                             fill = gcolors),
                                         nrow = 5, title.position = "top")) +
  scale_size(range = c(1, 5), breaks = c(1, 10, 20), limits = c(0, 20),
             name = "# of samples",
             guide = guide_legend(order = 3, override.aes = list(fill = "black"),
                                  nrow = 5, title.position = "top")) +
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "#f0f8ff"),
        panel.border = element_rect(fill = NA),
        plot.title = element_text(size = 16),
        axis.title = element_text(size = 14), 
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.margin = margin(0,0,0,0)) +
  ggtitle(title)
dev.off()
```
```{r}
pdf("./outputs/figures/Fig1_samples_sites_map_bathymetry_051123.pdf", width = 8, height = 6)
marmap::autoplot.bathy(panama, geom=c("r", "c"), color = "white", size = 0.01) + 
  scale_fill_etopo(name = "Depth (m)") + 
  new_scale_fill() +
  geom_point(data = samples_sites,
             aes(x = `Longitude`, y = `Latitude`, size = `n`, fill = `Region:Site`),
             shape = 21, alpha = 0.9, color = "black", stroke = 0.5,
             position = position_jitter(width = 0.1, height = 0.1, seed = 3),
             show.legend = T) +
  scale_fill_manual(values = site_colors,
                    guide = guide_legend(order = 2,
                                         override.aes = list(size = 6,
                                                             shape = 21, 
                                                             fill = site_colors),
                                         nrow = 12, title.position = "top")) +
  scale_size(range = c(1, 5), breaks = c(1, 10, 20), limits = c(0, 20),
             name = "# of samples",
             guide = guide_legend(order = 3, override.aes = list(fill = "black"),
                                  nrow = 5, title.position = "top")) +
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "#f0f8ff"),
        panel.border = element_rect(fill = NA),
        plot.title = element_text(size = 16),
        axis.title = element_text(size = 14), 
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.margin = margin(0,0,0,0)) +
  ggtitle(title)
dev.off()
```

```{r}
marmap::autoplot.bathy(east_pacific, geom=c("r", "c"), colour="white", size=0.1) + scale_fill_etopo()
```
```{r}
pdf("../outputs/figures/Fig1_etp_samples_sites_map_bathymetry_051223.pdf", width = 8, height = 8)
title <- expression('Eastern Pacific '*italic("Pocillopora")*' sample locations (n = 122 samples total)')
marmap::autoplot.bathy(east_pacific, geom=c("r", "c"), color = "white", size = 0.01) + 
  scale_fill_etopo(name = "Depth (m)") + 
  new_scale_fill() +
  geom_point(data = samples_sites,
             aes(x = `Longitude`, y = `Latitude`, size = `n`, fill = `Region:Site`),
             shape = 21, alpha = 0.9, color = "black", stroke = 0.5,
             position = position_jitter(width = 0.1, height = 0.1, seed = 3),
             show.legend = T) +
  scale_fill_manual(values = site_colors,
                    guide = guide_legend(order = 2,
                                         override.aes = list(size = 3,
                                                             shape = 21, 
                                                             fill = site_colors),
                                         nrow = 14, title.position = "top")) +
  scale_size(range = c(1, 6), breaks = c(1, 10, 20), limits = c(0, 20),
             name = "# of samples",
             guide = guide_legend(order = 3, override.aes = list(fill = "black"),
                                  nrow = 5, title.position = "top")) +
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "#f0f8ff"),
        panel.border = element_rect(fill = NA),
        plot.title = element_text(size = 14),
        axis.title = element_text(size = 10), 
        axis.text = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.margin = margin(0,0,0,0)) +
  ggtitle(title)
dev.off()
```
