#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q mThM.q
#$ -l mres=192G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N angsd_pgra_himb_ancestralfasta
#$ -o angsd_pgra_himb_ancestralfasta.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
 module load bioinformatics/angsd
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"

# making a list of sample names
# peffusa_reference_samples.txt
set=$1
#files=$(ls /scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim/data/raw/)
#samples=$(echo "$files" | cut -d . -f 1 | sort -u)
samples=$(cat ${prodir}/data/${set}_samples.txt)

# assign variable for output directory
setdir="${prodir}/outputs/angsd/${set}"

# making a list of bam file paths
ls ${prodir}/outputs/alignments/pgra_himb/*md.rg.bam | grep -f ${prodir}/data/${set}_samples.txt > ${setdir}/${set}_pgra_bamfile.txt

# verify samples are correct
echo " These are the samples to be processed: ${samples}, there are $(cat ${setdir}/${set}_pgra_bamfile.txt | wc -l) in total"

# assign variable to bamfile
BAMS=${setdir}/${set}_pgra_bamfile.txt
# 
REF=${mcs}/sequences/p_grandis_GCA_964027065.2/GCA_964027065.2_jaPocGran1.hap1.2_genomic.fna
OUT=${prodir}/data/seqs/${set}_pgra_himb_ancestral

# modified from http://www.popgen.dk/angsd/index.php/Fasta, section "Ancestral fasta using multiple outgroups"

angsd -b $BAMS -out $OUT -ref $REF -doFasta 2 -doCounts 1 -snp_pval 0.01 -doMaf 1 -doMajorMinor 1 -GL 2 -explode 1 -P $NSLOTS
# -rmSNPs 1 -minInd 1 -setMinDepthInd 1

echo = `date` job $JOB_NAME done