#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q mThM.q
#$ -l mres=192G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N angsd_depth_summary
#$ -o angsd_depth_summary.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
 module load bioinformatics/angsd
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

# specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"

# making a list of sample names
set=$1
#files=$(ls /scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim/data/raw/)
#samples=$(echo "$files" | cut -d . -f 1 | sort -u)
samples=$(cat ${prodir}/data/${set}_samples.txt)

# creating an output directory for set output files
if [ ! -d "${prodir}/outputs/angsd/${set}" ]; then mkdir ${prodir}/outputs/angsd/${set}; fi

# assign variable for output directory
setdir="${prodir}/outputs/angsd/${set}"

# making a list of bam file paths
ls ${prodir}/outputs/alignments/pgra_himb/*md.rg.bam | grep -f ${prodir}/data/${set}_samples.txt > ${setdir}/${set}_pgra_bamfile.txt

# verify samples are correct
echo " These are the samples to be processed: ${samples}, there are $(cat ${setdir}/${set}_pgra_bamfile.txt | wc -l) in total"

# assign variable to bamfile
BAMS=${setdir}/${set}_pgra_bamfile.txt

# from https://github.com/z0on/ClonesAndClades_Ofav_Keys/blob/master/read_processing_walkthrough.txt
# Manzello et al. 2018

# ----- Depth and quality score distributions with ANGSD
#FILTERS:
# (ALWAYS record your filter settings and explore different combinations to confirm that results are robust. )
# set minInd to 50% of total number of samples
nsamps=$(cat $BAMS | wc -l) 
minindv=$(echo "$nsamps*0.5" | bc | awk '{print int($1+0.5)}')
# also adding  filters against very badly non-HWE sites (such as, all calls are heterozygotes => lumped paralog situation) and sites with really bad strand bias:
FILTERS="-uniqueOnly 1 -remove_bads 1 -minMapQ 30 -minInd $minindv"

#TODO: 
# -GL 1 : use samtools likelihood model
# -doQsDist 1 : 
# -doDepth 1 :
# -doCounts 1 : 
# -dumpCounts 2 :
TODO="-doQsDist 1 -doDepth 1 -doCounts 1 -dumpCounts 2"

angsd -b $BAMS -GL 1 $FILTERS $TODO -maxDepth 3000 -P $NSLOTS -out ${setdir}/${set}_pgra_dd_3000

echo = `date` job $JOB_NAME done