#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q mThM.q
#$ -l mres=192G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N angsd_ancestralfasta
#$ -o angsd_ancestralfasta.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
 module load bioinformatics/angsd
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"

BAMS=${prodir}/outputs/alignments/peffusa_bamfile.txt
OUT=${prodir}/data/seqs/peffusa_ancestral.fasta

# modified from http://www.popgen.dk/angsd/index.php/Fasta, section "Ancestral fasta using multiple outgroups"

angsd -b $BAMS -out $OUT -doCounts 1 -snp_pval 0.01 -doMaf 1 -doMajorMinor 1 -GL 2 -rmSNPs 1 -minind 4 -setMinDepthInd 10 -explode 1

echo = `date` job $JOB_NAME done