#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q mThM.q
#$ -l mres=96G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N angsd_SAF_2DSFS_genetic_divergence
#$ -o angsd_SAF_2DSFS_genetic_divergence.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
 module load bio/angsd/0.940 
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"
angsddir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim/outputs/angsd"

# making a list of no-clones sample names and bam file paths for each population / species
# list of populations
POPFILE="$1"
# generate list of populations
POPS=$(cat ${prodir}/data/pops/$POPFILE)

for set in $POPS; do 
# make bam file list
ls ${prodir}/outputs/alignments/*md.rg.bam | grep -f ${prodir}/data/pops/${set} > ${angsddir}/bamfiles/${set}_bamfile.txt
# verify sample numbers are correct
echo "For ${set}, There are $(cat ${angsddir}/bamfiles/${set}_bamfile.txt | wc -l) samples in total"
done

# 1) calculate SAF for each species/population
echo "Begin SAF estimation for each species/population"
for set in $POPS; do 
echo "${set} SAF estimation"
# ----- SAF with ANGSD
# specify variable with bam file list for each population / species
BAMS="${angsddir}/bamfiles/${set}_bamfile.txt"
# filters are not needed since we are restricting the SAF estimation to previously filtered sites (AllSites)
# -doSaf 1: perform multisample GL estimation
TODO=" -doSaf 1"
# set ancestral reference genome fasta file
#ANC="/scratch/nmnh_corals/connellym/sequences/pdam/pdam_genome.fasta"
ANC="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim/data/seqs/peffusa_reference_ancestral.fa"

# estimate the site allele frequency likelihood
angsd -sites ${angsddir}/AllSites.txt -rf ${angsddir}/SczhEnG.txt -b $BAMS -anc $ANC -GL 1 -P $NSLOTS $TODO -out ${angsddir}/${set} 
echo "DONE!"
done

# 2) now create wrapper jobs to calculate the 2D SFS for all pairwise comparisons
echo "Begin 2D SFS calculation for all combinations"
# loop to create and submit separate jobs for all pairwise 2DSFS calculations
set -- $POPS
for pop1; do
shift
for pop2; do
# create job file
echo "Creating job file for pairwise 2D SFS estimation of ${pop1} and ${pop2}"
JOBFILE="${prodir}/bash/jobs/angsd_2DSFS_${pop1}.${pop2}.job"
touch $JOBFILE
# input QSUB commands
echo "#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q mThM.q
#$ -l mres=96G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N angsd_2DSFS_${pop1}.${pop2}
#$ -o ${prodir}/bash/jobs/angsd_2DSFS_${pop1}.${pop2}.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bio/angsd/0.940
#
# ----------------Your Commands------------------- #
#" >> $JOBFILE
# input job-specific variables
echo 'echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"
angsddir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim/outputs/angsd"
#' >> $JOBFILE
# input ANGSD commands
printf 'realSFS ${angsddir}/%s.saf.idx ${angsddir}/%s.saf.idx -P $NSLOTS > ${angsddir}/%s.%s.ml \n' "$pop1" "$pop2" "$pop1" "$pop2" >> $JOBFILE
# input job finished statment
echo '#
echo = `date` job $JOB_NAME done' >> $JOBFILE
#qsub $JOBFILE
done
done

echo = `date` job $JOB_NAME done