# /bin/sh 
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -q lThC.q
#$ -l mres=8G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N bcftools_subset
#$ -o bcftools_subset.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/bcftools
module load bioinformatics/vcflib
module load bioinformatics/vcftools
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
bcftools view /scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim/outputs/all_analysis.vcf.gz | vcfrandomsample -r 0.002 > /scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim/outputs/all_analysis_subset.vcf
#
echo = `date` job $JOB_NAME done
