#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 24
#$ -q lThC.q
#$ -l mres=72G,h_data=3G,h_vmem=3G
#$ -cwd
#$ -j y
#$ -N exabayes_phyluce
#$ -o exabayes_phyluce.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/exabayes
#
# ----------------Your Commands------------------- #

echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"

# specify which taxon set and alignment to use
set=$1
# make output directory
mkdir ${prodir}/outputs/exabayes/exabayes_${set}
#
exabayes-mpi -np $NSLOTS \
-f ${prodir}/outputs/uce-taxon-sets/${set}-mafft-nexus-internal-trimmed-gblocks-clean-75p-raxml/${set}-mafft-nexus-internal-trimmed-gblocks-clean-75p.phylip \
-m DNA \
-q ${prodir}/outputs/uce-taxon-sets/${set}-mafft-nexus-internal-trimmed-gblocks-clean-75p-raxml/${set}-mafft-nexus-internal-trimmed-gblocks-clean-75p.partitions \
-w ${prodir}/outputs/exabayes/exabayes_${set} \
-n ${set} \
-s 12345 \
-R 4 

echo = `date` job $JOB_NAME done