# /bin/sh 
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 24
#$ -q lThM.q
#$ -l mres=288G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N kraken_build_default
#$ -o kraken_build_default.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/kraken
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"
DBNAME="${prodir}/data/krakendb/kraken_db_default"

mkdir -p ${prodir}/data/krakendb

kraken2-build --standard --threads $NSLOTS --db $DBNAME
#
echo = `date` job $JOB_NAME done
