#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q mThM.q
#$ -l mres=192G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N mitofinder_CDS_align_mafft
#$ -o mitofinder_CDS_align_mafft.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/mafft
#
# ----------------Your Commands------------------- #

echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"

# purpose: align the extracted CDS for the 13 protein-coding genes and 2 tRNAs annotated in Mitofinder results, concatenate alignments for phylogenetic inference
mtgenes="ATP8 COX1 rrnL ND1 CYTB ND2 ND6 ATP6 ND4 rrnS COX3 COX2 ND4L ND3 ND5"
# align 
for gene in $mtgenes
do mafft --retree 2 --adjustdirection --thread $NSLOTS ${prodir}/outputs/mitofinder/cds_alignments/${gene}/${gene}_all.fasta > ${prodir}/outputs/mitofinder/cds_alignments/${gene}/${gene}_aligned.fasta
done
#
echo = `date` job $JOB_NAME done