#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 3
#$ -q sThC.q
#$ -l mres=24G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N sharkmer
#$ -o sharkmer.log
#
# ----------------Modules------------------------- #
  module load bio/sharkmer/0.2.0_93ee045
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME

# specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"

#
cat ${prodir}/data/sharkmer_samples.txt | while read SAMPLE 
do 
gunzip ${prodir}/data/trimmed/${SAMPLE}_R1_PE_trimmed.fastq.gz
gunzip ${prodir}/data/trimmed/${SAMPLE}_R2_PE_trimmed.fastq.gz

 sharkmer \
 --max-reads 1000000 \
 -s ${SAMPLE} -o ${prodir}/outputs/sharkmer/${SAMPLE}_sharkmer_output/ \
 --pcr "AACCTGGTTGATCCTGCCAGT,TGATCCTTCCGCAGGTTCACCT,3500,18S-AB-complete" \
  --pcr "AACCTGGTTGATCCTGCCAGT,CCAACTACGAGCTTTTTAACTG,1000,18S-AL-piece1" \
  --pcr "CGGTAATTCCAGCTCCAATAG,CAGACAAATCGCTCCACCAAC,1000,18S-CY-piece2" \
  --pcr "AAGGGCACCACCAGGAGTGGAG,TGATCCTTCCGCAGGTTCACCT,1000,18S-OB-piece3"  \
  --pcr "CCCSSGTAATTTAAGCATATTA,TCGGAAGGAACCAGCTAC,2000,28SrD1-B-piece1" \
  --pcr "CAAGGAGTCTAACACGTGCG,GAGTTGTTACACACTCCTTAGC,1000,28SHHW-piece2" \
  --pcr "ACCTATTCTCAAACTTTAAATGG,GACTTCCCTTACCTACAT,1000,28Srd48a-rd7-piece3" \
  --pcr "CCCSSGTAATTTAAGCATATTA,GACTTCCCTTACCTACAT,3500,28Srd1-rd7-complete"  \
  --pcr "CACGAGACCGATAGCGAACAAGTA,TCATTTCGACCCTAAGACCTC,4000,28SFar-28SRar" \
  --pcr "CACGAGACCGATAGCGAACAAGTA,TCGCTACGAGCTTCCACCAGTGTTT,4000,28SFar-28SRab" \
  --pcr "TTTGGGSATTCGTTTAGCAG,SCCAATATGTTAAACASCATGTCA,1500,mtORF" \
  --pcr "ATTCAGTCTCACTCACTCACTCAC,TATCTTCGAACAGACCCACCAAAT,1500,PocHistone" \
 ${prodir}/data/trimmed/${SAMPLE}_R1_PE_trimmed.fastq ${prodir}/data/trimmed/${SAMPLE}_R2_PE_trimmed.fastq 

gzip ${prodir}/data/trimmed/${SAMPLE}_R1_PE_trimmed.fastq
gzip ${prodir}/data/trimmed/${SAMPLE}_R2_PE_trimmed.fastq 
done 
#
echo = `date` job $JOB_NAME done

#TO RUN JOB - 
# All reads files should be unzipped (use gunzip command to do this)
# Include unique sample IDs in file names of read files = {SAMPLE}. 
# Create a text file called "sharkmer_samples.txt" with each unique sample name in a
# column (i.e., one sample name per line).
# Modify the input read files in script (e.g., ./${SAMPLE}_R1_PE_trimmed.fastq) as needed
# to match your file names for forward and reverse reads (usually contain R1 and R2).
# Run job file in same directory as read files and sharkmer_samples.txt file.

# NOTES -
# To add or remove primer sequences, edit the --pcr commands in script. Include forward
# and reverse primer sequences, estimated length (overestimate this length), and primer
# pair name.

