#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q mThM.q
#$ -l mres=192G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N vcftools_filter_sequence
#$ -o vcftools_filter_sequence.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/vcftools
module load bioinformatics/bcftools
#
# ----------------Your Commands------------------- #

echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"
gatkdir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim/outputs/gatk_vcf_filtering"

# filter to include only no-clones samples (n = 229)
vcftools --gzvcf ${gatkdir}/full_analysis.vcf.gz --keep ${prodir}/data/final_noclones_samples.txt \
--recode --stdout | gzip -c > ${gatkdir}/full_analysis_noclones.vcf.gz

# filter to include only "representative" samples for snapp species subset - top 5 from each K = 5 (n = 24)
vcftools --gzvcf ${gatkdir}/full_analysis.vcf.gz --keep ${prodir}/data/representative_5X_snapp_samples.txt \
--recode --stdout | gzip -c > ${gatkdir}/rep_5X_snapp_subset.vcf.gz

# filter to include only snapp K6 5X species subset samples (n = 29)
vcftools --gzvcf ${gatkdir}/full_analysis.vcf.gz --keep ${prodir}/data/representative_5X_plus3b_snapp_samples.txt \
--recode --stdout | gzip -c > ${gatkdir}/rep_5X_plus3b_snapp_subset.vcf.gz

### ------------------------------------------------

# filter SNPs in no-clones samples
vcftools --gzvcf ${gatkdir}/full_analysis_noclones.vcf.gz \
--minDP 10 --maxDP 300 --minQ 30 --maf 0.05 --max-missing 0.85 --remove-indels \
--recode --stdout | gzip -c > ${gatkdir}/full_analysis_noclones_filtered.vcf.gz

## population structure strict
vcftools --gzvcf ${gatkdir}/full_analysis_noclones.vcf.gz \
--minDP 10 --maxDP 300 --minQ 30 --maf 0.05 --max-missing 0.95 --thin 5000 --hwe 0.000001 --remove-indels \
--recode --stdout | gzip -c > ${gatkdir}/full_analysis_noclones_filtered_strict.vcf.gz
### assess missing data, 
vcftools --gzvcf ${gatkdir}/full_analysis_noclones_filtered_strict.vcf.gz --missing-indv --stdout > ${gatkdir}/full_analysis_noclones_filtered_strict.imiss
awk '$5 < 0.05 {print $1}' ${gatkdir}/full_analysis_noclones_filtered_strict.imiss > ${prodir}/data/full_analysis_noclones_filtered_strict_imiss05_samples.txt
### keep samples with <5% missing data 
vcftools --gzvcf ${gatkdir}/full_analysis_noclones_filtered_strict.vcf.gz --keep ${prodir}/data/full_analysis_noclones_filtered_strict_imiss05_samples.txt \
--recode --stdout | gzip -c > ${gatkdir}/full_analysis_noclones_filtered_strict_imiss05.vcf.gz

## population structure relaxed
vcftools --gzvcf ${gatkdir}/full_analysis_noclones.vcf.gz \
--minDP 10 --maxDP 300 --minQ 30 --maf 0.05 --max-missing 0.5 --hwe 0.01 --remove-indels \
--recode --stdout | gzip -c > ${gatkdir}/full_analysis_noclones_filtered_relaxed.vcf.gz
### assess missing data
vcftools --gzvcf ${gatkdir}/full_analysis_noclones_filtered_relaxed.vcf.gz --missing-indv --stdout > ${gatkdir}/full_analysis_noclones_filtered_relaxed.imiss
awk '$5 < 0.5 {print $1}' ${gatkdir}/full_analysis_noclones_filtered_relaxed.imiss > ${prodir}/data/full_analysis_noclones_filtered_relaxed_imiss50_samples.txt
### keep samples with <50% missing data 
vcftools --gzvcf ${gatkdir}/full_analysis_noclones_filtered_relaxed.vcf.gz --keep ${prodir}/data/full_analysis_noclones_filtered_relaxed_imiss50_samples.txt \
--recode --stdout | gzip -c > ${gatkdir}/full_analysis_noclones_filtered_relaxed_imiss50.vcf.gz

### ------------------------------------------------

# filter SNPs in snapp spp subset samples 
vcftools --gzvcf ${gatkdir}/rep_5X_snapp_subset.vcf.gz \
--minDP 10 --maxDP 300 --minQ 30 --maf 0.05 --max-missing 0.85 --remove-indels \
--recode --stdout | gzip -c > ${gatkdir}/rep_5X_snapp_subset_filtered.vcf.gz

# filter SNPs for unlinked, 0% missing data for SNAPP tree, BFD* analyses
vcftools --gzvcf ${gatkdir}/rep_5X_snapp_subset.vcf.gz \
--minDP 10 --maf 0.05 --thin 5000 --max-missing 1 --remove-indels \
--recode --stdout | gzip -c > ${gatkdir}/rep_5X_snapp_subset_nomissing_thinned.vcf.gz

### ------------------------------------------------

# filter SNPs in snapp spp subset samples plus 3b
vcftools --gzvcf ${gatkdir}/rep_5X_plus3b_snapp_subset.vcf.gz \
--minDP 10 --maxDP 300 --minQ 30 --maf 0.05 --max-missing 0.85 --remove-indels \
--recode --stdout | gzip -c > ${gatkdir}/rep_5X_plus3b_snapp_subset_filtered.vcf.gz

# filter SNPs for unlinked, 0% missing data for SNAPP tree, BFD* analyses
vcftools --gzvcf ${gatkdir}/rep_5X_plus3b_snapp_subset.vcf.gz \
--minDP 10 --maf 0.05 --thin 5000 --max-missing 1 --remove-indels \
--recode --stdout | gzip -c > ${gatkdir}/rep_5X_plus3b_snapp_subset_nomissing_thinned.vcf.gz