# /bin/sh 
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -q sThC.q
#$ -l mres=8G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N vcftools_summary
#$ -o vcftools_summary.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/vcftools
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
VCF_NAME="$1"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"
outdir="${prodir}/outputs/vcf_filtering/${VCF_NAME}"
VCF_IN="${prodir}/outputs/vcf_filtering/${VCF_NAME}.vcf.gz"
mkdir $outdir
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --depth
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --site-mean-depth
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --geno-depth
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --missing-indv
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --missing-site
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --indv-freq-burden
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --freq2
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --singletons
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --012
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --het
vcftools --gzvcf $VCF_IN --out ${outdir}/${VCF_NAME} --site-quality
#
echo = `date` job $JOB_NAME done
